#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$updateCommand = new \Rlweb\JSONResume\Dev\UpdateCommand('update');
$application = new Application();
$application->add($updateCommand);
$application->setDefaultCommand($updateCommand->getName());
$application->run();